export default defineNuxtConfig({
  ssr: true,
  compatibilityDate: '2026-04-18',
  modules: ['@nuxtjs/tailwindcss', '@nuxt/image', '@nuxt/content'],
  css: ['~/css/globals.css'],
  runtimeConfig: {
    public: {
      siteUrl: 'https://kura-finance.com',
    },
  },
  experimental: {
    payloadExtraction: true,
  },
  app: {
    head: {
      htmlAttrs: { lang: 'en' },
      title: 'Kura Finance — The Super Financial App',
      meta: [
        { charset: 'utf-8' },
        { name: 'viewport', content: 'width=device-width, initial-scale=1' },
        { name: 'description', content: 'Trade crypto, RWA, and US stocks. Spend with Kura Card. Track all your finances in one self-custody super app.' },
        { name: 'author', content: 'Kura Finance' },
        { name: 'theme-color', content: '#FAF8F3' },
        { name: 'apple-mobile-web-app-capable', content: 'yes' },
        { name: 'apple-mobile-web-app-status-bar-style', content: 'default' },
        { name: 'apple-mobile-web-app-title', content: 'Kura Finance' },
        { property: 'og:site_name', content: 'Kura Finance' },
        { property: 'og:locale', content: 'en_US' },
        { property: 'og:type', content: 'website' },
        { property: 'og:image', content: 'https://kura-finance.com/Unified-finance-dashboard.webp' },
        { property: 'og:image:alt', content: 'Kura Finance — The Super Financial App' },
        { name: 'twitter:card', content: 'summary_large_image' },
        { name: 'twitter:image', content: 'https://kura-finance.com/Unified-finance-dashboard.webp' },
        { name: 'robots', content: 'index, follow' },
      ],
      link: [
        { rel: 'icon', type: 'image/svg+xml', href: '/favicon.svg' },
        { rel: 'apple-touch-icon', href: '/icon.webp' },
        { rel: 'mask-icon', href: '/favicon.svg', color: '#8B5CF6' },
        { rel: 'sitemap', href: '/sitemap.xml', type: 'application/xml' },
        { rel: 'alternate', type: 'application/rss+xml', title: 'Kura Blog RSS', href: '/feed.xml' },
      ],
    },
  },
  image: {
    format: ['webp'],
    quality: 80,
    screens: {
      xs: 320,
      sm: 640,
      md: 768,
      lg: 1024,
    },
  },
  nitro: {
    prerender: {
      crawlLinks: true,
      routes: ['/sitemap.xml', '/feed.xml'],
    },
    compressPublicAssets: true,
  },
  routeRules: {
    '/': { prerender: true },
    '/about': { prerender: true },
    '/pricing': { prerender: true },
    '/download': { prerender: true },
    '/kura-wallet': { prerender: true },
    '/kura-card': { prerender: true },
    '/trackfi': { prerender: true },
    '/help': { prerender: true },
    '/docs': { prerender: true },
    '/blog': { prerender: true },
    '/blog/**': { prerender: true },
    '/feed.xml': { prerender: true },
    '/sitemap.xml': { prerender: true },
    '/docs/stock-countries': { prerender: true },
    '/docs/card-countries': { prerender: true },
    '/docs/on-off-ramp-countries': { prerender: true },
    '/resources/stock-countries': { redirect: { to: '/docs/stock-countries', statusCode: 301 } },
    '/resources/card-countries': { redirect: { to: '/docs/card-countries', statusCode: 301 } },
    '/resources/on-off-ramp-countries': { redirect: { to: '/docs/on-off-ramp-countries', statusCode: 301 } },
    '/community': { prerender: true },
    '/business': { prerender: true },
    '/privacy': { prerender: true },
    '/tos': { prerender: true },
    '/disclaimer': { prerender: true },
    '/compliance': { prerender: true },
    '/_nuxt/**': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
    '/icon.webp': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
    '/favicon.svg': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
    '/Unified-finance-dashboard.webp': { headers: { 'cache-control': 'public, max-age=31536000, immutable' } },
  },
  tailwindcss: {
    configPath: '~/tailwind.config.ts',
    viewer: false,
  },
  devtools: { enabled: false },
});
