<template>
  <div class="w-full text-kura-text bg-white">
    <PageHero
      eyebrow="Legal"
      title="Referral Program Terms"
      description="Last updated: July 16, 2026. Rules for earning referral revenue share on Kura."
    />

    <div class="marketing-container max-w-3xl pb-20 md:pb-28">
      <div class="prose max-w-none space-y-8">
        <section>
          <p class="text-kura-text-secondary leading-relaxed text-sm border border-kura-border rounded-xl p-4 bg-kura-background">
            These Referral Program Terms (the “Program Terms”) supplement the
            <NuxtLink to="/tos" class="text-kura-primary hover:text-kura-accent">Terms of Service</NuxtLink>.
            For referral matters, these Program Terms control over conflicting ToS provisions, except dispute resolution, liability limits, and general provisions in the ToS. Capitalized terms not defined here have the meanings in the ToS.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">1. Program Overview</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            Kura may offer eligible users (“Referrers”) the opportunity to earn a revenue share on eligible platform revenue generated by users they invite (“Referred Users”). The current headline share is up to ten percent (10%) of Eligible Revenue, subject to these Program Terms and in-app program rules. Rewards are discretionary promotional benefits, not interest, deposits, wages, or guaranteed income. LI.FI process volume and similar third-party processing volume are not referral-eligible unless expressly stated in-app.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">2. Eligibility</h2>
          <ul class="list-disc pl-6 mt-3 space-y-2 text-kura-text-secondary leading-relaxed">
            <li>Referrer and Referred User must have valid Kura accounts in good standing and comply with the ToS and
              <NuxtLink to="/prohibited-activities" class="text-kura-primary hover:text-kura-accent">Prohibited Activities List</NuxtLink>.</li>
            <li>Self-referrals, circular referrals, and referrals between accounts controlled by the same person or household are prohibited.</li>
            <li>Employees, contractors, and agents of Kura may be excluded unless we state otherwise.</li>
            <li>Referred Users must be new to Kura (no prior account under substantially the same identity or wallet cluster, as determined by Kura).</li>
            <li>Geographic, sanctions, and partner eligibility limits apply.</li>
          </ul>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">3. How Referrals Work</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            You may share a referral code or link we provide. Attribution is determined by our systems when the Referred User signs up using your code/link within the attribution window shown in-app. We are not responsible for failed attribution due to ad blockers, delayed installs, or user error. Referring participants may see referral status (for example signup or qualifying activity) but not the Referred User’s personal information or full transaction details.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">4. Eligible Revenue</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            “Eligible Revenue” means fees actually earned by Kura from a Referred User’s qualifying activity as defined in-app from time to time — which may include subscription fees and certain platform fees — net of refunds, chargebacks, credits, taxes, payment-processor fees, and amounts we reasonably determine are non-qualifying. Unless expressly included in-app, the following are not Eligible Revenue: partner pass-through fees, network gas, LI.FI or bridge notional volume, Morpho protocol fees paid to third parties, card interchange not retained by Kura, and one-time promotional credits.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">5. Calculation, Pending Periods, and Payouts</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            Rewards accrue according to the rate and schedule shown in-app, may be held in a pending state for a review period (for example to cover refunds or fraud checks), and are paid in the form and currency or asset we designate. We may set minimum payout thresholds, caps, or offsets. You are responsible for any taxes arising from rewards and for providing tax information we reasonably request. Unclaimed rewards may expire after a period we specify in-app or after account closure.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">6. Fraud, Forfeiture, and Clawback</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            We may withhold, reverse, claw back, or cancel rewards (including already paid amounts where recoverable) if we reasonably believe there was fraud, abuse, ToS violation, chargebacks/refunds, duplicate accounts, artificial volume, or inaccurate information. We may suspend referral privileges pending investigation. Our determination is final and binding, subject to mandatory consumer law.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">7. Program Changes and Termination</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            We may modify, suspend, or discontinue the Program or any rate, cap, or eligibility rule at any time. Where required by law we will provide reasonable notice. Changes do not create vested rights to future rewards. Upon termination of the Program or your participation, unpaid pending rewards may be cancelled except where we are legally required to pay them.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">8. Disclaimers and Liability</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            The Program is provided “as is.” Liability related to the Program is subject to the disclaimer and limitation-of-liability sections of the ToS. Rewards may have no value until paid and may be affected by asset price changes if paid in digital assets.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">9. Error Reporting</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            Report apparent calculation or payout errors to
            <a href="mailto:support@kura-finance.com" class="text-kura-primary hover:text-kura-accent">support@kura-finance.com</a>
            within thirty (30) days of the date the reward was credited or should have been credited. Failure to report within that period waives related claims to the fullest extent permitted by law.
          </p>
        </section>

        <section>
          <h2 class="text-2xl font-bold text-kura-text mb-4">10. Governing Law</h2>
          <p class="text-kura-text-secondary leading-relaxed">
            These Program Terms are governed by the dispute-resolution and governing-law provisions of the ToS.
          </p>
        </section>
      </div>

      <div class="mt-16 pt-8 border-t border-kura-border">
        <NuxtLink to="/tos" class="text-kura-primary hover:text-kura-accent transition-colors">
          ← Back to Terms of Service
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: 'default',
})

usePageSeo({
  title: 'Referral Program Terms',
  description:
    'Kura referral program terms covering eligibility, eligible revenue, clawback, and payouts.',
  path: '/referral-terms',
  keywords: 'referral program, revenue share, Kura Finance LLC legal',
})
</script>
